version: "3.9"
services:
    web:
        image: node:12.18.3
        networks:
            - default
        ports:
            - "4001:4001"
        volumes:
            - .:/nodeapp
        working_dir: /nodeapp
        command: npm run start